version: '2'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      # Uncomment this line if you want to use your own Envoy with WASM enabled.
      #- /tmp/envoy-docker-build/envoy/source/exe/envoy:/usr/local/bin/envoy
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

networks:
  envoymesh: {}
